DROP TABLE Customers;

CREATE TABLE Customers(
CustomerID VARCHAR(25) NOT NULL,
CompanyName VARCHAR(25) NOT NULL,
ContactName VARCHAR(25) NOT NULL,
Address VARCHAR(25) NOT NULL,
City VARCHAR(25) NOT NULL,
Region VARCHAR(25) NOT NULL,
PostalCode VARCHAR(25) NOT NULL,
Country VARCHAR(25) NOT NULL,
tel VARCHAR(25) NOT NULL,
FAX VARCHAR(25) NOT NULL
);